In [16]:
import numpy as np

In [35]:
x1 = [
    [
      [4, 2, -1],
      [1, -5, 2],
      [2, -1, -4]
    ],
    [
      [3, 4, 5],
      [-3, 7, -4],
      [1, -4, -2]
    ],
    [
      [9, -2, 3, 2],
      [2, 8, -2, 3],
      [-3, 2, 11, -4],
      [-2, 3, 2, 10]
    ]
]
y1 = [
    [41, -10, 1],
    [34, -32, 62],
    [55, -14, 12, -21]
]

In [36]:
def cekDiagonallyDominant(x):
  #ubah dulu x1 menjadi array
  x = np.array(x)
  #mengambil nilai diagonal + absolut (x)
  diag = np.diag(np.abs(x))
  #cari jumlah dari setiap baris selain nilai diagonal +absolut(X)
  off_diag = np.sum(np.abs(x),axis = 1) - diag
  #axis =1 penjumlahan terhadap row
  if np.all(diag > off_diag):
    return True
  else:
    return False

In [38]:
def gauss_seidel(x,y,epsilon=0.022,t=15):
  #panggil function cekdiagonallyDominant
  if not cekDiagonallyDominant(x):
    print("not diagonally dominant")
    return
  #mengubah x1 dan y1 menjadi array
  x = np.array(x)
  y = np.array(y)
# mengambil nilai diagonal
  diag = np.diag(np.abs(x))
  #menegasikan array x
  x = -x
  #fill value diagonal array x menjadi 0
  np.fill_diagonal(x,0)
  #inisialisai value
  mat_old = np.zeros(x[0].shape)
  #melakukan iterasi
  for i in range(t):
    mat_new = np.array(mat_old)
    for j, row in enumerate(x):
      mat_new[j] = (y[j] + np.dot(row,mat_new)) / diag[j]
    print(f"iterasi ke-{i}")
    print(mat_new)

    dx = np.sqrt(np.dot(mat_new - mat_old,mat_new - mat_old))

    if(dx < epsilon):
      print("converged")
      return
    mat_old = mat_new

  print("not converged")
  return


In [41]:
#implementasi function gauss_seidel ke lebih dari satu matrix
for i, (X,Y) in enumerate(zip(x1,y1)):
  print(f"persamaan ke-{i + 1}")
  gauss_seidel(X,Y)
  print("======================================")

persamaan ke-1
iterasi ke-0
[10.25   -4.05   -5.8875]
iterasi ke-1
[10.803125   -1.805625   -5.60296875]
iterasi ke-2
[ 9.75207031 -1.70922656 -5.0533418 ]
iterasi ke-3
[ 9.84127783 -1.94691885 -5.15736863]
iterasi ke-4
[ 9.93411727 -1.923876   -5.19802763]
iterasi ke-5
[ 9.91243109 -1.90327516 -5.18203434]
iterasi ke-6
[ 9.906129   -1.90841206 -5.18016752]
converged
persamaan ke-2
not diagonally dominant
persamaan ke-3
iterasi ke-0
[ 6.11111111 -3.27777778  3.35353535 -0.56515152]
iterasi ke-1
[ 4.39046016 -1.79729938  2.40957938 -1.16463403]
iterasi ke-2
[ 5.16732568 -2.00269881  2.44080351 -0.95388592]
iterasi ke-3
[ 5.06444041 -2.04820201  2.49765287 -0.97218189]
iterasi ke-4
[ 5.03944457 -2.02087972  2.47921505 -0.98169018]
iterasi ke-5
[ 5.05377509 -2.02550619  2.48050699 -0.97769452]
converged
